// Gemini resilience tests: 503 (overloaded) and 429 (quota) must not end the interview while another
// retry, model or key can still answer. Everything is still generated by (fake) Gemini: no canned lines.
// Plain node, no network, no npm install:   cd backend && node test/gemini-routes.test.mjs
import { register } from 'node:module';

Object.assign(process.env, {
  GEMINI_API_KEY: 'key1',
  GEMINI_BACKUP_KEYS: 'key2',
  GEMINI_MODEL: 'main-flash',
  GEMINI_FALLBACK_MODELS: 'backup-flash',
  GEMINI_TURN_TIMEOUT_MS: '9000',
  GEMINI_BRIEFING_TIMEOUT_MS: '9000',
});

// Fake Gemini: globalThis.__script["model|key"] is a queue of outcomes ('503', '429', '404'); empty = success.
const FAKE_GENAI = `
export class GoogleGenAI {
  constructor({ apiKey }) {
    this.models = {
      generateContent: async (req) => {
        const route = req.model + '|' + apiKey;
        globalThis.__calls.push(route);
        const next = (globalThis.__script[route] || []).shift();
        if (next === '503') throw new Error('{"error":{"code":503,"message":"The model is overloaded. Please try again later.","status":"UNAVAILABLE"}}');
        if (next === '429') throw new Error('{"error":{"code":429,"message":"You exceeded your current quota","status":"RESOURCE_EXHAUSTED"}}');
        if (next === '404') throw new Error('{"error":{"code":404,"message":"models/' + req.model + ' is not found","status":"NOT_FOUND"}}');
        const briefing = Boolean(req.config?.responseJsonSchema?.properties?.interviewerName) || /Design the interviewer/.test(String(req.contents));
        return { text: JSON.stringify(briefing ? globalThis.__briefing : globalThis.__turn) };
      },
    };
  }
}`;
register(
  'data:text/javascript,' +
    encodeURIComponent(`export async function resolve(spec, ctx, next) {
      if (spec === '@google/genai') return { url: 'data:text/javascript,' + encodeURIComponent(${JSON.stringify(FAKE_GENAI)}), shortCircuit: true };
      try { return await next(spec, ctx); }
      catch (err) { if (spec === 'dotenv/config') return { url: 'data:text/javascript,', shortCircuit: true }; throw err; }
    }`),
);

globalThis.__briefing = {
  company: 'CrowdStrike', companyContext: 'Falcon platform.', team: 'OverWatch', interviewerName: 'Maya Chen',
  interviewerTitle: 'Senior Manager', interviewerBackground: 'Hunts.', roleSummary: 'Hunt threats.', mustHaves: ['EDR'],
  strongSignals: 'Hypotheses.', redFlags: [], interviewPlan: [{ topic: 'a', why: '' }, { topic: 'b', why: '' }, { topic: 'c', why: '' }],
};
globalThis.__turn = { heard: '', answerRead: 'first_turn', reaction: "I'm Maya Chen on OverWatch.", question: 'What EDR work have you done?', action: 'ask' };

const iv = await import('../src/interviewer.js');

let passed = 0;
let failed = 0;
function check(name, cond, detail = '') {
  if (cond) passed++;
  else failed++;
  console.log(`${cond ? 'PASS' : 'FAIL'}  ${name}${!cond && detail ? `  -> ${String(detail).slice(0, 400)}` : ''}`);
}
let n = 0;
async function scenario(script) {
  iv._resetGeminiRoutes();
  globalThis.__calls = [];
  globalThis.__script = JSON.parse(JSON.stringify(script));
  // New role each time so the interviewer briefing (cached per setup) is rebuilt: 2 calls per scenario when healthy.
  try {
    return { value: await iv.nextTurn({ persona: 'cold', role: `Threat Hunter ${++n}`, history: [], state: 'calm', questionCount: 0, maxQuestions: 5 }) };
  } catch (error) {
    return { error };
  }
}

let r = await scenario({});
check('[ok] healthy: briefing + turn on the main model and key', r.value?.source === 'gemini' && globalThis.__calls.join() === 'main-flash|key1,main-flash|key1', globalThis.__calls.join());

r = await scenario({ 'main-flash|key1': ['503'] });
check('[503 once] retried on the same route and succeeded', r.value?.source === 'gemini' && globalThis.__calls.slice(0, 2).join() === 'main-flash|key1,main-flash|key1', globalThis.__calls.join());

r = await scenario({ 'main-flash|key1': ['503', '503'] });
check('[503 twice] moved to the backup key, same model', r.value?.source === 'gemini' && globalThis.__calls.includes('main-flash|key2'), globalThis.__calls.join());
check('[503 twice] the next call starts on the route that worked', globalThis.__calls.at(-1) === 'main-flash|key2', globalThis.__calls.join());

r = await scenario({ 'main-flash|key1': ['429'] });
check('[429] no retry on an exhausted route, straight to the backup key', r.value?.source === 'gemini' && globalThis.__calls[0] === 'main-flash|key1' && globalThis.__calls[1] === 'main-flash|key2', globalThis.__calls.join());

r = await scenario({ 'main-flash|key1': ['429'], 'main-flash|key2': ['429'] });
check('[429 both keys] fell back to the backup model', r.value?.source === 'gemini' && globalThis.__calls.includes('backup-flash|key1'), globalThis.__calls.join());

r = await scenario({ 'main-flash|key1': ['404'], 'main-flash|key2': ['404'] });
check('[404 model] unknown model skipped for good, backup model used', r.value?.source === 'gemini' && globalThis.__calls.filter((c) => c.startsWith('main-flash')).length === 2, globalThis.__calls.join());

const all429 = { 'main-flash|key1': ['429'], 'main-flash|key2': ['429'], 'backup-flash|key1': ['429'], 'backup-flash|key2': ['429'] };
r = await scenario(all429);
check('[429 everywhere] clear InterviewerError, no canned line', r.error?.code === 'AI_INTERVIEWER_FAILED', r.error?.message || JSON.stringify(r.value));
check('[429 everywhere] message says quota and how to fix it', /quota used up \(429\)/.test(r.error?.message) && /GEMINI_BACKUP_KEYS/.test(r.error?.message), r.error?.message);

const all503 = {};
for (const k of Object.keys(all429)) all503[k] = ['503', '503'];
r = await scenario(all503);
check('[503 everywhere] clear "overloaded" error', r.error?.code === 'AI_INTERVIEWER_FAILED' && /overloaded right now/.test(r.error.message), r.error?.message);
check('[503 everywhere] tried every route before giving up', new Set(globalThis.__calls).size === 4, globalThis.__calls.join());

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
